name: producto

services:
  api:
    command: ["npm", "run", "dev"]
    volumes:
      - ../services/api:/producto/services/api
      - ../tools:/producto/tools
      - ../node_modules:/producto/node_modules

  product:
    command: ["npm", "run", "dev"]
    volumes:
      - ../services/product:/producto/services/product
      - ../tools:/producto/tools
      - ../database:/producto/database
      - ../node_modules:/producto/node_modules

  elasticsync:
    command: ["npm", "run", "dev"]
    volumes:
      - ../services/elasticsync:/producto/services/elasticsync
      - ../database:/producto/database
      - ../node_modules:/producto/node_modules

  trade:
    command: ["npm", "run", "dev"]
    volumes:
      - ../services/trade:/producto/services/trade
      - ../tools:/producto/tools
      - ../database:/producto/database
      - ../node_modules:/producto/node_modules
      - ../products.json:/producto/products.json